export { default as covid } from './covid.png';
export { default as goggle } from './goggle.png';
export { default as instagram } from './instagram.png';
export { default as isitopen } from './isitopen.png';
export { default as pitchbooker } from './pitchbooker.png';
export { default as plant } from './plant.jpg';
export { default as terygram } from './terygram.png';
export { default as todolist } from './todolist.png';
export { default as oldportfolio } from './oldportfolio.png';
